name: Deploy FancyCore (release)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '24'

      - name: Modify gradlew permissions
        run: chmod +x ./gradlew

      - name: Build
        env:
          RELEASE_CHANNEL: 'release'
        run: ./gradlew :plugins:fancycore:shadowJar

      - name: Deploy
        uses: fancyinnovations/fancyverteiler@main
        with:
          config_path: "/plugins/fancycore/release_deployment_config.json"
          modtale_api_key: ${{ secrets.MODTALE_API_KEY }}
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}

      #      - name: Publish to reposilite (releases)
      #        run: ./gradlew :plugins:fancycore:fc-api:publishAllPublicationsToFancyinnovationsReleasesRepository

      #      - name: Publish to reposilite (snapshots)
      #        run: ./gradlew :plugins:fancycore:fc-api:publishAllPublicationsToFancyinnovationsSnapshotsRepository